"""Coder Agent (blueprint §9-10).

A coder claims a task, works inside an isolated worktree, produces the
task's files and reports structured output. It never touches `main`
directly - the orchestrator merges accepted output.

Two backends:
    RecipeBackend - deterministic in-process generator (no API key).
                    Used for the demo / E2E test. Can inject a seeded bug
                    to exercise the repair loop for real.
    OpenAIBackend - optional, real LLM coding via an OpenAI-compatible API.
                    Enabled only when OPENAI_API_KEY is present.
"""
from __future__ import annotations

import os
from pathlib import Path

from ..schemas.base import AgentOutput, Evidence, Risk, Severity
from .base import AgentInput

COMPANY_MODULE = """\
\"\"\"calculator - sample product module generated by the factory.

Example: a tiny calculator service used to demonstrate the
Coder -> Verifier -> Reviewer -> Merge loop end to end.
\"\"\"


def add(a: float, b: float) -> float:
    return a + b


def sub(a: float, b: float) -> float:
    return a - b


def mul(a: float, b: float) -> float:
    return a * b


def div(a: float, b: float) -> float:
    \"\"\"Divide a by b. Raises ZeroDivisionError when b == 0.\"\"\"
    return a / b
"""

COMPANY_TESTS = """\
import pytest

from sample_app.calc import add, div, mul, sub


def test_add():
    assert add(2, 3) == 5
    assert add(-1, 1) == 0


def test_sub():
    assert sub(5, 3) == 2


def test_mul():
    assert mul(2, 7) == 14
    assert mul(0, 100) == 0


def test_div():
    assert div(10, 2) == 5
    assert div(7, 2) == pytest.approx(3.5)


def test_div_by_zero_raises():
    with pytest.raises(ZeroDivisionError):
        div(1, 0)
"""

# Same tests, but the target function has an off-by-one style bug the
# verifier will reliably catch: sub computes a + b instead of a - b.
COMPANY_MODULE_BUGGY = COMPANY_MODULE.replace(
    "def sub(a: float, b: float) -> float:\n    return a - b",
    "def sub(a: float, b: float) -> float:\n    return a + b  # BUG: should be '-'",
)

INIT_PY = ""


def _write(parent: Path, rel: str, content: str) -> Path:
    dst = parent / rel
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(content, encoding="utf-8")
    return dst


class RecipeBackend:
    """Deterministic generator used for demo/E2E without any API key."""

    name = "recipe"

    def __init__(self, inject_bug: bool = False):
        self._inject_bug = inject_bug

    def run(self, task: AgentInput) -> AgentOutput:
        workdir = Path(task.workdir)
        target = task.context.get("target", "all")
        (workdir / "sample_app").mkdir(parents=True, exist_ok=True)
        (workdir / "tests").mkdir(parents=True, exist_ok=True)
        module_src = COMPANY_MODULE_BUGGY if self._inject_bug else COMPANY_MODULE

        files: list[str] = []
        if target in ("all", "scaffold"):
            _write(workdir, "sample_app/__init__.py", INIT_PY)
            _write(workdir, "sample_app/calc.py", module_src)
            files += ["sample_app/__init__.py", "sample_app/calc.py"]
        if target in ("all", "tests"):
            _write(workdir, "tests/test_calc.py", COMPANY_TESTS)
            files += ["tests/test_calc.py"]
        evidence = [
            Evidence(
                kind="generated_files",
                detail=", ".join(files),
                value=float(len(files)),
            )
        ]
        risks = []
        if self._inject_bug:
            risks.append(
                Risk(
                    severity=Severity.WARNING,
                    area="correctness",
                    description="seeded bug active in sub() to exercise repair loop",
                )
            )
        return AgentOutput(
            status="completed",
            summary="implemented sample_app package with unit tests",
            artifacts=files,
            tests=["tests/test_calc.py"],
            risks=risks,
            evidence=evidence,
        )


class OpenAIBackend:
    """Optional real-LLM coding backend (OpenAI-compatible).

    Requires OPENAI_API_KEY; otherwise the factory uses RecipeBackend.
    """

    name = "openai"

    def __init__(self, model: str | None = None):
        self._model = model or os.environ.get("OPENAI_MODEL", "gpt-4o-mini")
        self._client = self._build_client()

    @staticmethod
    def _build_client():
        import openai  # lazy import; optional dependency

        return openai.OpenAI(
            api_key=os.environ["OPENAI_API_KEY"],
            base_url=os.environ.get("OPENAI_BASE_URL"),
        )

    def __getstate__(self):
        # The httpx client behind openai.OpenAI is not picklable; the factory
        # moves coder attempts into a spawned process (hard-timeout isolation),
        # so we drop the live client here and rebuild it on the other side.
        state = self.__dict__.copy()
        state.pop("_client", None)
        return state

    def __setstate__(self, state):
        self.__dict__.update(state)
        self._client = self._build_client()

    def run(self, task: AgentInput) -> AgentOutput:
        system = (
            "You are a senior backend engineer. Produce ONLY the file contents "
            "as JSON: {\"files\": {\"rel/path.py\": \"content\"}}. "
            "Accompany each module with tests under tests/."
        )
        user = (
            f"Task {task.task_id}: {task.goal}\n"
            f"Acceptance: {task.acceptance_criteria}\n"
            f"Workdir: {task.workdir}"
        )
        try:
            resp = self._client.chat.completions.create(
                model=self._model,
                messages=[
                    {"role": "system", "content": system},
                    {"role": "user", "content": user},
                ],
                temperature=0,
            )
            content = resp.choices[0].message.content if resp.choices else None
        except Exception as exc:
            # A model-layer failure (network, auth, rate limit, malformed
            # upstream response) is a *failed attempt*, never a factory
            # crash. Shaped as a failed AgentOutput so the orchestrator can
            # route it through the normal repair loop / budget accounting
            # instead of an unhandled exception blowing up the whole run.
            return AgentOutput(
                status="failed",
                summary=f"LLM backend error: {exc!r}",
            )
        return self._apply(task, content or "{}")

    @staticmethod
    def _apply(task: AgentInput, payload: str) -> AgentOutput:
        import json

        from ..safety import safe_join

        try:
            start = payload.find("{")
            end = payload.rfind("}")
            data = json.loads(payload[start : end + 1])
        except Exception:
            return AgentOutput(status="failed", summary="LLM returned invalid JSON")
        files = data.get("files", {})
        if not isinstance(files, dict):
            return AgentOutput(
                status="failed", summary="LLM returned malformed files payload"
            )
        workdir = Path(task.workdir)
        written: list[str] = []
        for rel, content in files.items():
            if not isinstance(rel, str) or not isinstance(content, str):
                return AgentOutput(
                    status="failed",
                    summary="LLM returned non-string file key/value; refusing write",
                )
            try:
                dst = safe_join(workdir, rel)
            except ValueError as exc:
                # LLM output is untrusted: a path that could escape the
                # worktree aborts the whole batch - never touch the disk.
                return AgentOutput(
                    status="failed", summary=f"unsafe path from LLM rejected: {exc}"
                )
            dst.parent.mkdir(parents=True, exist_ok=True)
            dst.write_text(content, encoding="utf-8")
            written.append(rel)
        return AgentOutput(
            status="completed",
            summary=f"LLM wrote {len(written)} files",
            artifacts=written,
        )


class CoderAgent:
    def __init__(self, backend=None):
        self.backend = backend or self._auto_backend()

    @staticmethod
    def _auto_backend():
        if os.environ.get("OPENAI_API_KEY"):
            return OpenAIBackend()
        return RecipeBackend()

    def run(self, task: AgentInput) -> AgentOutput:
        return self.backend.run(task)
